/* GENERATED by app/scripts/embed_bundle.mjs — do not edit.
 * Dashboard SPA bundle embedded for the LAN HTTP server (issue #7). */
#ifndef GM_WEB_ASSETS_H
#define GM_WEB_ASSETS_H
#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *path;        /* URI path as served ("/", "/assets/x.js") */
    const char *mime;
    const uint8_t *data;
    size_t len;
} gm_web_asset_t;

extern const gm_web_asset_t gm_web_assets[];
extern const size_t gm_web_assets_count;

/* Returns the asset whose served path matches, or NULL. */
const gm_web_asset_t *gm_web_find(const char *path);

#endif /* GM_WEB_ASSETS_H */
